"""Generate Python tables from the canonical language-independent JSON."""
import json
import shutil
import tomllib
from pathlib import Path
from pprint import pformat

root = Path(__file__).resolve().parent.parent
name = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))["package"]["name"]
tables = {p.stem: json.loads(p.read_text(encoding="utf-8")) for p in sorted((root / "tables").glob("*.json"))}
out = root / "py" / name / "_tables.py"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("# Generated by scripts/sync-python.py; edit tables/*.json instead.\nTABLES = " + pformat(tables, sort_dicts=False, width=100) + "\n", encoding="utf-8")

# Ship the canonical product page and license notices with Python artifacts.
shutil.copyfile(root / "README.md", root / "py/README.md")
licenses = root / "py/LICENSES"
licenses.mkdir(exist_ok=True)
for source in (root / "LICENSES").iterdir():
    if source.is_file():
        shutil.copyfile(source, licenses / source.name)
