#!/usr/bin/env bash
# Vendor the canonical tables and crate version into this package before
# packing. The repository keeps no duplicates: `tables/` and `Cargo.toml`
# at the cnumber root stay canonical; `src/generated/` is regenerated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/src/generated" "$ROOT/typst/generated" "$ROOT/py/cnumber"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$ROOT" "$VERSION" <<'EOF'
import json
import sys

here, root, version = sys.argv[1], sys.argv[2], sys.argv[3]
with open(f"{root}/tables/numbers.json", encoding="utf-8") as handle:
    numbers = json.load(handle)
out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const NUMBERS_TABLE: unknown = {json.dumps(numbers, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/tables.ts", "w", encoding="utf-8") as handle:
    handle.write(out)


def typst_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def typst_escape(value):
    return (
        value.replace('\\', '\\\\')
        .replace('"', '\\"')
        .replace('\u202f', '\\u{202f}')
        .replace('\u00a0', '\\u{a0}')
    )


def typst_entry(key, entry):
    fields = [
        f"decimal: \"{typst_escape(entry['decimal'])}\"",
        f"group: \"{typst_escape(entry['group'])}\"",
    ]
    if "amtlich_text_decimal" in entry:
        fields.append(f"amtlich_text_decimal: \"{typst_escape(entry['amtlich_text_decimal'])}\"")
    body = ", ".join(fields)
    return f"{typst_str(key)}: ({body})"


entries = ",\n    ".join(
    typst_entry(key, entry) for key, entry in numbers["locales"].items()
)
supported = ", ".join(typst_str(code) for code in numbers["supported"])
typ = (
    "// GENERATED by js/@corbet-foss/cnumber/scripts/sync-assets.sh — do not edit.\n"
    "#let numbers-table = (\n"
    f"  locales: (\n    {entries},\n  ),\n"
    f"  supported: ({supported}),\n"
    f"  fallback: {typst_str(numbers['fallback'])},\n"
    ")\n"
)
with open(f"{root}/typst/generated/numbers.typ", "w", encoding="utf-8") as handle:
    handle.write(typ)
print(f"synced tables/numbers.json, version {version}")
EOF

python3 "$ROOT/scripts/sync-python.py"
